import type { Product } from '@/types/Product'

export const mockProducts: Product[] = [
  {
    id: 1,
    name: 'Bluetooth Headphones',
    price: 1499.99,
    category: 'Electronics',
    image: 'https://picsum.photos/seed/1/400/300',
    description: 'Wireless headphones with high‑fidelity sound.',
  },
  {
    id: 2,
    name: 'Sports Water Bottle',
    price: 299.0,
    category: 'Sports',
    image: 'https://picsum.photos/seed/2/400/300',
    description: 'Leak‑proof bottle perfect for workouts.',
  },
  {
    id: 3,
    name: 'Yoga Mat',
    price: 599.0,
    category: 'Fitness',
    image: 'https://picsum.photos/seed/3/400/300',
    description: 'Eco‑friendly yoga mat with non‑slip surface.',
  },
  {
    id: 4,
    name: 'Laptop Stand',
    price: 899.5,
    category: 'Office',
    image: 'https://picsum.photos/seed/4/400/300',
    description: 'Adjustable stand for better posture.',
  },
  {
    id: 5,
    name: 'Running Shoes',
    price: 2599.99,
    category: 'Footwear',
    image: 'https://picsum.photos/seed/5/400/300',
    description: 'Lightweight and durable for everyday jogs.',
  },
  {
    id: 6,
    name: 'Coffee Grinder',
    price: 1249.0,
    category: 'Kitchen',
    image: 'https://picsum.photos/seed/6/400/300',
    description: 'Manual grinder with adjustable settings.',
  },
  {
    id: 7,
    name: 'Wireless Mouse',
    price: 499.0,
    category: 'Electronics',
    image: 'https://picsum.photos/seed/7/400/300',
    description: 'Ergonomic design with long battery life.',
  },
  {
    id: 8,
    name: 'Desk Lamp',
    price: 749.0,
    category: 'Office',
    image: 'https://picsum.photos/seed/8/400/300',
    description: 'LED lamp with adjustable brightness.',
  },
  {
    id: 9,
    name: 'Fitness Tracker',
    price: 1999.0,
    category: 'Fitness',
    image: 'https://picsum.photos/seed/9/400/300',
    description: 'Track your daily activity and sleep.',
  },
  {
    id: 10,
    name: 'Cookware Set',
    price: 3499.0,
    category: 'Kitchen',
    image: 'https://picsum.photos/seed/10/400/300',
    description: 'Non‑stick pots and pans for everyday use.',
  },
  {
    id: 11,
    name: 'Bluetooth Speaker',
    price: 1799.0,
    category: 'Electronics',
    image: 'https://picsum.photos/seed/11/400/300',
    description: 'Portable speaker with deep bass.',
  },
  {
    id: 12,
    name: 'Gaming Keyboard',
    price: 2499.0,
    category: 'Gaming',
    image: 'https://picsum.photos/seed/12/400/300',
    description: 'RGB backlit mechanical keyboard.',
  },
  {
    id: 13,
    name: 'Backpack',
    price: 1199.0,
    category: 'Fashion',
    image: 'https://picsum.photos/seed/13/400/300',
    description: 'Water‑resistant with laptop compartment.',
  },
  {
    id: 14,
    name: 'Sunglasses',
    price: 799.0,
    category: 'Fashion',
    image: 'https://picsum.photos/seed/14/400/300',
    description: 'UV‑protected stylish sunglasses.',
  },
  {
    id: 15,
    name: 'Electric Kettle',
    price: 999.0,
    category: 'Kitchen',
    image: 'https://picsum.photos/seed/15/400/300',
    description: 'Quick boil and auto shut‑off feature.',
  },
  {
    id: 16,
    name: 'Notebook Set',
    price: 399.0,
    category: 'Office',
    image: 'https://picsum.photos/seed/16/400/300',
    description: 'Set of 3 ruled notebooks.',
  },
  {
    id: 17,
    name: 'Jump Rope',
    price: 249.0,
    category: 'Fitness',
    image: 'https://picsum.photos/seed/17/400/300',
    description: 'Adjustable and durable jump rope.',
  },
  {
    id: 18,
    name: 'LED Strip Lights',
    price: 899.0,
    category: 'Home Decor',
    image: 'https://picsum.photos/seed/18/400/300',
    description: 'Multicolor lights with remote control.',
  },
  {
    id: 19,
    name: 'Hair Dryer',
    price: 1299.0,
    category: 'Beauty',
    image: 'https://picsum.photos/seed/19/400/300',
    description: 'Fast drying with heat control.',
  },
  {
    id: 20,
    name: 'Travel Mug',
    price: 499.0,
    category: 'Kitchen',
    image: 'https://picsum.photos/seed/20/400/300',
    description: 'Keeps drinks hot or cold for hours.',
  },
  {
    id: 21,
    name: 'Wireless Charger',
    price: 1099.0,
    category: 'Electronics',
    image: 'https://picsum.photos/seed/21/400/300',
    description: 'Fast charging pad for smartphones.',
  },
  {
    id: 22,
    name: 'T‑shirt',
    price: 399.0,
    category: 'Fashion',
    image: 'https://picsum.photos/seed/22/400/300',
    description: '100% cotton, available in multiple colors.',
  },
  {
    id: 23,
    name: 'Face Mask Pack',
    price: 249.0,
    category: 'Beauty',
    image: 'https://picsum.photos/seed/23/400/300',
    description: 'Hydrating and soothing skin masks.',
  },
  {
    id: 24,
    name: 'Smart Watch',
    price: 3499.0,
    category: 'Electronics',
    image: 'https://picsum.photos/seed/24/400/300',
    description: 'Fitness and notifications in one device.',
  },
  {
    id: 25,
    name: 'Beanie Hat',
    price: 299.0,
    category: 'Fashion',
    image: 'https://picsum.photos/seed/25/400/300',
    description: 'Warm knit hat for winter.',
  },
  {
    id: 26,
    name: 'Monitor Stand',
    price: 649.0,
    category: 'Office',
    image: 'https://picsum.photos/seed/26/400/300',
    description: 'Raises monitor to eye level.',
  },
  {
    id: 27,
    name: 'Wireless Earbuds',
    price: 1899.0,
    category: 'Electronics',
    image: 'https://picsum.photos/seed/27/400/300',
    description: 'Compact design with charging case.',
  },
  {
    id: 28,
    name: 'Graphic Tee',
    price: 499.0,
    category: 'Fashion',
    image: 'https://picsum.photos/seed/28/400/300',
    description: 'Trendy print on soft fabric.',
  },
  {
    id: 29,
    name: 'Mini Projector',
    price: 5999.0,
    category: 'Electronics',
    image: 'https://picsum.photos/seed/29/400/300',
    description: 'Portable and easy to set up.',
  },
  {
    id: 30,
    name: 'Electric Toothbrush',
    price: 1299.0,
    category: 'Health',
    image: 'https://picsum.photos/seed/30/400/300',
    description: 'Deep cleaning with timer.',
  },
  {
    id: 31,
    name: 'Laptop Bag',
    price: 1499.0,
    category: 'Office',
    image: 'https://picsum.photos/seed/31/400/300',
    description: 'Sleek design with padded interior.',
  },
  {
    id: 32,
    name: 'Camping Tent',
    price: 3599.0,
    category: 'Outdoor',
    image: 'https://picsum.photos/seed/32/400/300',
    description: 'Waterproof and wind‑resistant.',
  },
  {
    id: 33,
    name: 'Action Camera',
    price: 4999.0,
    category: 'Electronics',
    image: 'https://picsum.photos/seed/33/400/300',
    description: '4K waterproof adventure cam.',
  },
  {
    id: 34,
    name: 'Electric Fan',
    price: 1799.0,
    category: 'Home Appliances',
    image: 'https://picsum.photos/seed/34/400/300',
    description: 'Quiet and energy‑efficient cooling.',
  },
  {
    id: 35,
    name: 'Baking Set',
    price: 1199.0,
    category: 'Kitchen',
    image: 'https://picsum.photos/seed/35/400/300',
    description: 'Everything you need for cookies and cakes.',
  },
  {
    id: 36,
    name: 'Wireless Router',
    price: 2499.0,
    category: 'Electronics',
    image: 'https://picsum.photos/seed/36/400/300',
    description: 'High‑speed internet for the whole home.',
  },
  {
    id: 37,
    name: 'Dumbbell Set',
    price: 3499.0,
    category: 'Fitness',
    image: 'https://picsum.photos/seed/37/400/300',
    description: 'Adjustable weights for your workout.',
  },
  {
    id: 38,
    name: 'Wall Clock',
    price: 699.0,
    category: 'Home Decor',
    image: 'https://picsum.photos/seed/38/400/300',
    description: 'Modern design, silent movement.',
  },
  {
    id: 39,
    name: 'Desk Organizer',
    price: 399.0,
    category: 'Office',
    image: 'https://picsum.photos/seed/39/400/300',
    description: 'Declutter your workspace in style.',
  },
  {
    id: 40,
    name: 'Gaming Chair',
    price: 5999.0,
    category: 'Gaming',
    image: 'https://picsum.photos/seed/40/400/300',
    description: 'Ergonomic chair with lumbar support.',
  },
]
